# Site wide configuration

title: ESM 296-4f
description: "A lightweight site starter for Jekyll"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //ucsb-bren.github.io/esm296-4f

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-coffeescript


# Site owner
owner:
  name: Michael Rose
  web: http://mademistakes.com
  email: michael@mademistakes.com
  twitter: mmistakes
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +MichaelRoseDesign
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "vendor"]